name: Build and deploy resume

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.9"
          bundler-cache: true

      - name: Build resume
        run: ./build_resume.bash --resume-user timothyfisher --resume-name resume_dev_refined

      - name: Copy resume PDF
        run: cp ./TimothyFisher-Res-Dev.pdf ./dist/timothyfisher/resume_dev_refined/pdf/TimothyFisher-Res-Dev.pdf

      - name: Set up Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/timothyfisher/resume_dev_refined

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4